development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: log
      username: root
      password: gb004
test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: log-test 
      username: root
      password: gb004
